package microvm

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/lambdamicrovms"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

const (
	// DefaultMicroVMPort is the Lambda MicroVM endpoint's default target port.
	// Requests that do not include X-aws-proxy-port are routed to port 8080
	// inside the MicroVM.
	DefaultMicroVMPort = int32(8080)
)

// AllIngressConnectorARN returns the AWS-managed ingress connector ARN that
// enables inbound HTTPS access to all application ports allowed by the auth
// token.
func AllIngressConnectorARN(region string) string {
	return fmt.Sprintf("arn:aws:lambda:%s:aws:network-connector:aws-network-connector:ALL_INGRESS", region)
}

// InternetEgressConnectorARN returns the AWS-managed egress connector ARN that
// enables outbound public internet access from a MicroVM.
func InternetEgressConnectorARN(region string) string {
	return fmt.Sprintf("arn:aws:lambda:%s:aws:network-connector:aws-network-connector:INTERNET_EGRESS", region)
}

// NoIngressConnectorARN returns the AWS-managed ingress connector ARN that
// disables inbound connectivity for a MicroVM.
func NoIngressConnectorARN(region string) string {
	return fmt.Sprintf("arn:aws:lambda:%s:aws:network-connector:aws-network-connector:NO_INGRESS", region)
}

// ShellIngressConnectorARN returns the AWS-managed ingress connector ARN
// required for MicroVM shell access and debugging.
func ShellIngressConnectorARN(region string) string {
	return fmt.Sprintf("arn:aws:lambda:%s:aws:network-connector:aws-network-connector:SHELL_INGRESS", region)
}

// Manager coordinates the common Lambda MicroVM workflow.
//
// It packages application files, uploads artifacts to S3, calls the Lambda
// MicroVMs control-plane API through the AWS SDK for Go v2, and creates
// Session values that send authenticated HTTP requests to running MicroVM
// endpoints.
type Manager struct {
	s3  s3API
	mvm microvmsAPI

	httpClient *http.Client

	bucket         string
	artifactPrefix string
	baseImageARN   string
	buildRoleARN   string

	defaultIngress []string
	defaultEgress  []string
	pollInterval   time.Duration
}

// Config configures a Manager.
type Config struct {
	// AWSConfig is used to construct default S3 and Lambda MicroVMs SDK clients
	// when S3Client or MicroVMClient are not supplied.
	AWSConfig aws.Config

	// S3Client overrides the S3 client used to upload MicroVM image artifacts.
	// If nil, NewManager creates one from AWSConfig.
	S3Client *s3.Client
	// MicroVMClient overrides the Lambda MicroVMs control-plane client. If nil,
	// NewManager creates one from AWSConfig.
	MicroVMClient *lambdamicrovms.Client
	// HTTPClient is used by Session to call MicroVM HTTPS endpoints. If nil,
	// http.DefaultClient is used.
	HTTPClient *http.Client

	// ArtifactBucket is the default S3 bucket for zip artifacts generated by
	// BuildImage and BuildImageFromDir. It can be overridden per build request.
	ArtifactBucket string
	// ArtifactPrefix is an optional S3 key prefix used when BuildImage generates
	// an artifact key automatically.
	ArtifactPrefix string
	// BaseImageARN is the default Lambda-managed MicroVM base image ARN used by
	// CreateMicrovmImage. It can be overridden per build request.
	BaseImageARN string
	// BuildRoleARN is the default IAM role ARN that Lambda assumes during image
	// creation to read the S3 artifact and write build logs.
	BuildRoleARN string

	// DefaultIngressConnectors are used by Run when the request does not specify
	// ingress network connectors. Use AllIngressConnectorARN, NoIngressConnectorARN,
	// or ShellIngressConnectorARN for AWS-managed connectors.
	DefaultIngressConnectors []string
	// DefaultEgressConnectors are used by Run when the request does not specify
	// egress network connectors. Use InternetEgressConnectorARN for public
	// internet access or provide a customer-managed VPC connector ARN.
	DefaultEgressConnectors []string
	// PollInterval controls the default delay between GetMicrovmImage and
	// GetMicrovm polling attempts. If zero, NewManager uses 2 seconds.
	PollInterval time.Duration
}

// NewManager constructs a Manager from Config.
//
// When SDK clients are not supplied, AWSConfig.Region must be set so the AWS
// SDK can resolve regional S3 and Lambda MicroVMs endpoints.
func NewManager(cfg Config) (*Manager, error) {
	s3Client := cfg.S3Client
	if s3Client == nil {
		if cfg.AWSConfig.Region == "" {
			return nil, errors.New("microvm: AWSConfig.Region is required when S3Client is not provided")
		}
		s3Client = s3.NewFromConfig(cfg.AWSConfig)
	}

	microvmClient := cfg.MicroVMClient
	if microvmClient == nil {
		if cfg.AWSConfig.Region == "" {
			return nil, errors.New("microvm: AWSConfig.Region is required when MicroVMClient is not provided")
		}
		microvmClient = lambdamicrovms.NewFromConfig(cfg.AWSConfig)
	}

	httpClient := cfg.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	pollInterval := cfg.PollInterval
	if pollInterval <= 0 {
		pollInterval = 2 * time.Second
	}

	return &Manager{
		s3:             s3Client,
		mvm:            microvmClient,
		httpClient:     httpClient,
		bucket:         cfg.ArtifactBucket,
		artifactPrefix: cfg.ArtifactPrefix,
		baseImageARN:   cfg.BaseImageARN,
		buildRoleARN:   cfg.BuildRoleARN,
		defaultIngress: append([]string(nil), cfg.DefaultIngressConnectors...),
		defaultEgress:  append([]string(nil), cfg.DefaultEgressConnectors...),
		pollInterval:   pollInterval,
	}, nil
}
